import asyncio
from src.services.llm_adapter import get_llm
from src.services.antigravity_workflow import allowed_call
from src.utils.prompt_hardening import harden_prompt

class ChatAgent:
    def __init__(self):
        self.llm = get_llm()

    async def generate_reply(self, req):
        botId = getattr(req, "botId", None) or (req.get("botId") if isinstance(req, dict) else None)
        event = "meeting"
        if not allowed_call(botId, event):
            # rate-limited: return a lightweight canned reply to obey zero-cost rule
            parts = ["hmm", "i dont know"]
            return parts, "skipped LLM (rate limited)"
        prompt = harden_prompt(req.meetingContext if hasattr(req, "meetingContext") else req.get("meetingContext", {}))
        resp = await self.llm.generate(prompt)
        parts = resp.split("|")[:2]
        return parts, "generated by " + self.llm.__class__.__name__
